Adiciona testes do RequestProvider
Sysvale/sys-hand-on-wheel pull request #1
Opened 2022-02-24 13:24 UTC by lucasn4s

Configura ambiente de testes do projeto, além de criar testes para o componente RequestProvider

## Testando

- Execute `npm install`;
- Rode os testes unitários, utilizando o comando `npm run test:unit`;
- Verifique o código para se certificar de que todas as partes importantes do funcionamento do componente foram testadas corretamente;
- Deixe seu like e se inscreva no canal.

2022-03-02 13:23 UTC, tassiocaique commented on package.json
> +  "version": "0.1",
Quando eu tento rodar o comando `npm run test:unit` retorna um erro de "versão inválida".

Modificar a versão para "0.1.0" resolve o problema

2022-03-02 13:27 UTC, tassiocaique commented on src/components/__tests__/RequestProvider.spec.js
> +const payloadResolverMock = jest.fn((payload) => convertKeysToCamelCase(payload));
Acredito que o uso do `convertKeysToCamelCase` e do `convertKeysToSnakeCase` é desnecessário nesse mock visto que esses "resolvers" já são padrão dentro do componente. Talvez fosse útil fazer um teste com esse resolvers que não sejam esse padrão. Ex.: Um teste onde se envie snake e receba snake, etc.

2022-03-02 19:07 UTC, lucasn4s commented on src/components/__tests__/RequestProvider.spec.js
> +const payloadResolverMock = jest.fn((payload) => convertKeysToCamelCase(payload));
Nos testes, eu usei em situações "trocadas". Onde é padrão no funcionamento normal do componente que se utilize um, eu utilizei o outro, e vice-versa. Justamente pra testar se os resolvers são chamados corretamente.

2022-03-04 11:36 UTC, patriciacoelho requested changes

2022-03-04 11:36 UTC, patriciacoelho commented on src/components/__tests__/RequestProvider.spec.js
> +test('Component renders correctly', async () => {
Acredito que não precise desse teste de snapshoot pois nada é renderizado graficamente

2022-03-07 13:51 UTC, lucasn4s commented on src/components/__tests__/RequestProvider.spec.js
> +test('Component renders correctly', async () => {
O teste de snapshot com um componente básico (a div no caso), garante que features que a gente implemente futuramente não renderizem nada indesejado.

2022-03-08 13:10 UTC, patriciacoelho approved these changes

2022-03-08 13:10 UTC, merged